export enum SupabaseErrorEnums {
  SUPABASE = 'SUPABASE',
  DB_PAUSED = 'DB_PAUSED',
  MISSING_CONFIG = 'MISSING_CONFIG',
}

export enum ServerErrorEnums {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  GUEST_DELETE_FAILED = 'GUEST_DELETE_FAILED',
  INVITE_DELETE_FAILED = 'INVITE_DELETE_FAILED',
  MISSING_INVITE_ID = 'MISSING_INVITE_ID',
  INVITE_NOT_FOUND = 'INVITE_NOT_FOUND',
  GUEST_NOT_FOUND = 'GUEST_NOT_FOUND',
  INVITE_SAVE_FAILED = 'INVITE_SAVE_FAILED',
  GUEST_SAVE_FAILED = 'GUEST_SAVE_FAILED',
  // Add more types as needed
}

export type ApiErrorType = SupabaseErrorEnums | ServerErrorEnums;
